package uk.gov.defra.tracesx.common.event.model;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TransactionCode {
  IPAFFS_USER_LOGIN("IPAFFS-USER-LOGIN"),
  IPAFFS_USER_DENY("IPAFFS-USER-DENY"),
  IPAFFS_REGULATOR_LOGIN("IPAFFS-REGULATOR-LOGIN"),
  IPAFFS_REGULATOR_DENY("IPAFFS-REGULATOR-DENY"),
  IPAFFS_SOAP_AUTH("IPAFFS-SOAP-AUTH"),
  IPAFFS_SOAP_FAIL("IPAFFS-SOAP-FAIL"),
  IPAFFS_PERMISSION_DENY("IPAFFS-PERMISSION-DENY"),
  IPAFFS_TC_ACCEPTED("IPAFFS-TC-ACCEPTED"),
  IPAFFS_PART1_COMPLETE("IPAFFS-PART1-COMPLETE"),
  IPAFFS_PART2_COMPLETE("IPAFFS-PART2-COMPLETE"),
  IPAFFS_PART3_COMPLETE("IPAFFS-PART3-COMPLETE"),
  IPAFFS_REENFORCED_CREATE("IPAFFS-REENFORCED-CREATE"),
  IPAFFS_REENFORCED_REMOVE("IPAFFS-REENFORCED-REMOVE"),
  IPAFFS_BORDERNOTIFICATION_CREATE("IPAFFS-BORDERNOTIFICATION-CREATE"),
  IPAFFS_BORDERNOTIFICATION_REMOVE("IPAFFS-BORDERNOTIFICATION-REMOVE"),
  IPAFFS_404("IPAFFS-404"),
  IPAFFS_5XX("IPAFFS-5XX"),
  IPAFFS_INPUT_VALIDATION_FAIL("IPAFFS-INPUT-VALIDATION-FAIL"),
  IPAFFS_HONEY_POT("IPAFFS-HONEY-POT"),
  IPAFFS_DYNAMICS_MESSAGE("IPAFFS-DYNAMICS-MESSAGE"),
  IPAFFS_DOCUMENT_UPLOAD_ATTEMPT("IPAFFS-DOCUMENT-UPLOAD-ATTEMPT"),
  IPAFFS_DOCUMENT_DOWNLOAD_ATTEMPT("IPAFFS-DOCUMENT-DOWNLOAD-ATTEMPT"),
  IPAFFS_ANTIVIRUS_CHECK("IPAFFS-ANTIVIRUS-CHECK"),
  IPAFFS_ANTIVIRUS_THREAT_DETECTED("IPAFFS-ANTIVIRUS-THREAT-DETECTED"),
  IPAFFS_BLOCKED_UPLOAD("IPAFFS-BLOCKED-UPLOAD"),
  IPAFFS_BLOCKED_DOWNLOAD("IPAFFS-BLOCKED-DOWNLOAD"),
  IPAFFS_ANTIVIRUS_CLEAN_UPLOAD("IPAFFS-ANTIVIRUS-CLEAN-UPLOAD"),
  IPAFFS_ANTIVIRUS_CLEAN_DOWNLOAD("IPAFFS-ANTIVIRUS-CLEAN-DOWNLOAD"),
  IPAFFS_REMOVED_DOCUMENT("IPAFFS-REMOVED-DOCUMENT");

  private String value;

  TransactionCode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }
}
